version: '3.9'

services:
  backend:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Eldar2002
    networks:
      - backend

  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: Eldar2002
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local